### ISSUE TITLE
Add support for "groups" inside ActionBody

### ISSUE THREAD

**Issue by mfulton26** [spekframework/spek#198]
I was surprised to learn that I can put `context` blocks inside `describe` and other `group` blocks but not inside `on` (`action`) blocks. I would like to be able to group `it` blocks within an `on`. e.g.:

```kotlin
describe("/persons") {
    val personsWebTarget = rootWebTarget.path("persons")
    on("GET") {
        val response by lazy { personsWebTarget.request().get() }
        it("should have response status 200 (OK) status code") {
            assertThat(response.status).isEqualTo(200)
        }
        context("Response Headers") {
            it("should have Transfer-Encoding: chunk") {
                assertThat(response.getHeaderString("Transfer-Encoding")).isEqualTo("chunked")
            }
            it("should have Date that satisfies RFC 7231 and is recent") {
                assertThat(Duration.between(response.date.toInstant(), Instant.now()))
                        .isLessThan(Duration.ofSeconds(3))
            }
            it("should have Content-Type: application/json;charset=UTF-8") {
                assertThat(response.mediaType)
                        .isEqualTo(MediaType.APPLICATION_JSON_TYPE.withCharset("UTF-8"))
            }
        }
        ...
    }
    ...
}
```

**Comment by raniejade** [comment]
Action blocks are treated as tests, so `group`s and `fixture`s are not allowed inside. Other than readability what are the benefits of having nested groups inside action blocks?

**Comment by mfulton26** [comment]
Just readability (organization).

I'm not familiar with `fixture`s.

What do you mean that action bodies are tests? The JUnit platform has containers and tests, right? Tests are leaves and cannot contain other tests was my understanding.

**Comment by mjdenham** [comment]
I found this confusing too.  I needed to start a mock web service before some tests and stop it after the tests so I used before/afterGroup with a context.  I also tried to use the verb on() within the context.  It took me a while to discover afterGroup() was running before on().

Could you clarify why on() is incompatible with beforeGroup/afterGroup.  The documentation seems a bit lacking regarding the details of the different verbs e.g. it was not clear that 'on' was an (the?) Action.

**Comment by raniejade** [comment]
During the discovery phase every call to  `group` and the fixtures (`beforeGroup`, `afterGroup`) are "collected" to build the test tree. The current engine requires to know about the groups and fixtures declared (test tree) in order to know the execution plan. Since `on` is implemented as an action scope, it is only executed during the execution phase. The engine wouldn't know about the fixtures declared in that scope, hence why we don't allow it.

We are aware of the problem regarding the docs and we currently reworking them.

**Comment by mfulton26** [comment]
Why distinguish between spec scope (`SpecBody`) and action scope (`ActionBody`)? I mean, why not just have all the groups (including `on`) be groups and all the tests be tests? This is how I understood previous version of Spek to work as well. Thanks.

**Comment by raniejade** [comment]
Actually @hhariri can best explain why we introduced action scopes `on`. People before tried adding state logic within group scopes, which doesn't behave as you might expect.

```kotlin
group("some group") {
   var foo = 1
   foo += 1

   test("verify foo == 2") { ... }

   foo += 1

   test("verify foo == 3") { ... }
}
```

As you can see the above spec won't work since, group scopes are eagerly evaluated during the discovery phase. It will fail on the first `test`, since `foo == 3` by the time the tests are executed. With action groups you get what you want.

```kotlin
action("some group") {
   var foo = 1
   foo += 1

   test("verify foo == 2") { ... }

   foo += 1

   test("verify foo == 3") { ... }
}
```

**Comment by hhariri** [comment]
I think we need to better describe this in our docs because `on` is just part of the `given` `on` `it` pattern, and really not there to be combined with `describe` `it` pattern. This might lead to confusion and unintended consequences.

**Comment by mfulton26** [comment]
In my opinion having `on` behave differently from the other `group` types is an unnecessary complexity. How about making all groups actions? Combine the discovery and execution phases into a single phase (i.e. discover while executing). This way spec developers can add state logic within any `group` (`describe`/`context`/`given`/`on`/etc.).

**Comment by raniejade** [comment]
That's a breaking change, I wouldn't want to change it.

**Comment by mfulton26** [comment]
Was changing `on` to an `action` not the same type of changing?

**Comment by raniejade** [comment]
`on` was changed because people expect it to behave the way it's now. Changing every group to behave like actions would break a lot of code.

**Comment by mfulton26** [comment]
Hmm. Okay. I actually expected all groups to behave like I understand
active do now the first time I used Spek but I realize I am only one data
point. Thank you for the info.

**Comment by mfulton26** [comment]
actions*

**Comment by raniejade** [comment]
That was one of my frustrations when using Spek for the first time. I started github.com/raniejade/kspec because of that and slow development. Soon enough while developing KSpec, I discovered the reason why we need a discovery phase - because of JUnit 4. To get proper reporting JUnit 4 runner requires the test plan to be known first before executing. 

Fixtures was introduced to circumvent the limitation of having a discovery phase. You could also use `memoized` if you want to put some setup in a group block.

```
group("my group") {
    val service by memoized { createMyService() }

    on("something") {
        val result = service.doSomething()

        it("verify") { assert.(result) }
    }
}
```

**Comment by mfulton26** [comment]
Is Spek still supporting JUnit 4 though? I thought they've completely moved to JUnit 5 (which doesn't have this issue from what I can tell).

**Comment by raniejade** [comment]
Yep we totally moved to JUnit 5, but it also have two phases - discovery and execution.

**Comment by mfulton26** [comment]
Yes, JUnit 5 does have two phases but you return a dynamic container in the discovery phase and then register dynamic containers and tests during the execution phase basically making it into a single phase.

**Comment by raniejade** [comment]
Last time I checked only dynamic tests are supported, not containers. Either way we will stick with the current behavior.

**Comment by mfulton26** [comment]
Very well. FYI: containers descriptors can be registered dynamically in JUnit 5 just like test descriptors can. In fact, I have a protect based on such that builds the tree completely dynamically. It works very well but then I would have to make my own plugin, source code location tooling, etc. which I would certainly rather not do.

Are there any reservations to a pull request to make the whole tree dynamic? Perhaps enabled with a flag of some sort or something?

**Comment by raniejade** [comment]
I'm not really keen in changing the current behavior, even adding just a flag. @hhariri @artem-zinnatullin what are your thoughts? It can potentially break *alot* of stuff, fixtures and subjects to name a few.

**Comment by hhariri** [comment]
The test suite of a project should be the most reliable aspect. Any breaking change like this I'm kind of against. We've already had one in the 1.1 and I believe we should aim to keep backwards compatibility unless it really goes against our goal to evolve Spek. A flag isn't that ideal cause it introduces again a change in behaviour that is not that apparent.

**Comment by artem-zinnatullin** [comment]
Even though I like and used to use `on` instead of `context`, I think we can't break compatibility again and as users have to just agree with current behavior of `on` and as maintainers of the project — improve documentation and reasoning behind it.

I understand your frustration, @mfulton26, but I hope you would agree that breaking changes are bad and we'll have to live with current behavior at least until 2.x release.

**Comment by mfulton26** [comment]
Yes, I do understand the need to avoid breaking changes. Perhaps this can be reviewed for a 2.x release.

On a side note, it looks like JUnit 5 will be adding top-level support for [dynamic containers](https://github.com/junit-team/junit5/issues/695#issuecomment-292914486).

**Comment by raniejade** [comment]
`action` is dropped in `2.x`.
