### ISSUE TITLE
Example of using JUnit5 for Java module in Android project

### ISSUE THREAD

**Issue by JolandaVerhoef** [spekframework/spek#254]
The website describes that in an Android project, you should use JUnit4. Using Spek with JUnit5 however gives an improved experience (xml result grouping, IDE plugin). https://github.com/JetBrains/spek/issues/52#issuecomment-283712210 indicates that with a few hacks, it should be possible to use JUnit5 for Java modules in an Android project.

What is the state on this? If this is actually possible, can you add documentation or an example configuration?

**Comment by heliofvj** [comment]
I was curious about this as well, so I created an Android project with a java-library module to check on the state of things.

Running spek tests in a java module from Android Studio does not seem to be possible ATM.
- After searching for a bit I found out that Android Studio uses an IntelliJ build that depends on APIs of an outdated JUnit 5 Milestone. Tests will fail when executed from Android Studio directly.
- Using JUnit M6 should solve the problem, but it persists. This time because kotlin classes won't be properly recognized.

I couldn't find a way to solve these issues, but there are alternatives:
- If you use the gradle console to run your tests, the problems above do not apply. This approach allows you to use spek with the latest release of JUnit 5.
- If you intend to use only Android modules in your project, the [android-junit](https://github.com/aurae/android-junit5) plugin by @aurae solves all the problems above. The github project has a sample showing how your project can be configured to run JUnit 5 based tests. This approach also allows you to use spek with the latest release of JUnit 5.
